name: Vercel Deployment DOE
env: 
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  
on: 
  push:
    branches:
      - main

jobs: 
  Deploy-development:
    runs-on: ubuntu-latest

    steps:
      - name: "checkout code"
        uses: actions/checkout@v4
      - name: Install Node.js 
        uses: actions/setup-node@v4

      - name: Install npm
        uses: actions/setup-node@v4
        with: 
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies 
        run: npm install

      - name: Install CLI
        run: npm install  --global vercel@latest

      - name: Pull Vercel Enviroment Information 
        run: vercel pull --yes --enviorment=development tokens=${{secrets.VERCEL_TOKEN_ID}}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN_ID}}

      - name: Deploy project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN_ID}} 

 

    
